### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by misterraj7** [SirCmpwn/RedditSharp#181] opened 2015-09-12 05:43 UTC
Can you please help with the documentation for the same if any available?

**Comment by SirCmpwn** [comment] 2015-09-12 12:32
Duplicate of #14

**Closed by SirCmpwn** 2015-09-12 12:32 UTC

**Comment by misterraj7** [comment] 2015-09-12 13:40
You may close this issue, but this doesnot have proper documentation. People like me seeking are having a tough time with the code. For instance I am seeking to post a link to Reddit but not sure how and where to see the code. 

There must be a cheat code for each and every major functions available, so that we can run and see the code.

**Comment by SirCmpwn** [comment] 2015-09-12 13:41
There is no "must" here. I don't have to cater to you. If you want to see a change in this project, you are expected to implement it yourself.

**Comment by misterraj7** [comment] 2015-09-12 14:11
agreed. There is no must. A well documented cheat code would help all those in need. Cheers!
